name: Test and Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: Gr1N/setup-poetry@v8
    - run: poetry --version
    - name: Install Dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          .
          !venv/
